### ISSUE TITLE
"Agreed" isn't stemmed correctly.

### ISSUE THREAD

**Issue by SudipShresthaCiena** [nemec/porter2-stemmer#4]
Agreed => Expected "Agree", result "Agre"

Step 1 correctly replaces "eed" with "ee".
Step 5 removes the last "e".

**Comment by nemec** [comment]
Hi @SudipShresthaCiena,

I believe the result is correct per the specification. It might make sense to have an exception here, but unfortunately I'm not involved with the Porter2 spec writing. If we take the word `agreed`, region _R1_ is _greed_ and _R2_ is the end of the word. With _eed_ replaced by _ee_ following Step 1, we look at Step 5. While _ee_ is in _R1_ and the word begins with a short syllable (_ag_), I believe the _r_ between _ag_ and _ee_ makes it so that Step 5 applies (it doesn't _directly_ follow a short syllable).

For reference, I found two online demos for this stemmer algorithm that match this repo's result (including, I believe, an official implementation of the algorithm)

<https://snowballstem.org/demo.html#English>
<http://proiot.ru/jssnowball/>
